### ISSUE TITLE
Player Data Reset (Sqlite)

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#290] opened 2019-05-30 22:53 UTC
Spigot account - https://www.spigotmc.org/members/alex_5678.438771/

Plugin version - 2.1.1.8

Spigot Version - git-Spigot-79a30d7-acbc348 (MC: 1.12.2)

Link to log file - https://pastebin.com/v2KEwMMi

Additional information - The Plugin itself runs fine. It stores the player data, player can use the quests, they can leave and join the server and the quests are stored.

But sometimes (as far as I know in the last 3 hours 4 out of about 80 players) the player data are completely reset (till now always after joining the server again)
so the player are not anymore in the leaderboard and they have to start the quests again.

(I thought about switching to MySQL (/MariaDB) but there I first have to solve this problem:https://github.com/JCulley/ProQuests-Documentation/issues/201 ...)

settings in config.yml:
database:
  use_mysql: false
  host: localhost
  port: '3306'
  database: database
  username: username
  password: password
  use_ssl: true
  join_delay: 5

**Comment by JCulley** [comment] 2019-05-30 23:10
First I do not provide support if you are not using the latest version. Secondly you have not provided your entire log. Lastly I would need much more information to investigate.

**Comment by ghost** [comment] 2019-05-30 23:30
1. The error uncured in 2.1.1.8. I now updated to 2.1.1.9
this was my mistake but due to the changelog this shouldn't change anything

2. Due to data protection I can not provide the full log file.
I can shorten it and then give it to you. in this case even this isn't possible due to the length of the log file.
If you want you can get all log entries from the start of proquests.

3. this are all information I can give you. If there is a debug mode in the plugin I will use it...

**Comment by JCulley** [comment] 2019-05-30 23:31
I cannot provide you support unless you provide me with your entire log file, sorry.

**Comment by ghost** [comment] 2019-05-30 23:37
by law I definitely can not publish this here.

I understand your position and the need to get to know all information surrounding this problem.
This is why I will definitely give you the information you ask for.

Else we will have to find another way to find the issue.

**Comment by JCulley** [comment] 2019-05-30 23:43
I’m sorry but there is not “another way” if you cannot provide me the logs then there’s nothing for me to investigate. If it’s working fine for everyone else and you can’t provide me the information I need then it’s  out of my hands. There’s no personal data whatsoever (excluding ips), otherwise having plaintext logs where you do have personal information exposed would be a privacy breach in itself. If you feel the need you can go through the file and scrub it of any personal data you wish however the entire log must be provided.

**Comment by JCulley** [comment] 2019-05-30 23:44
Additionally as I stated as well I would need far more information including specific times, players, and any other information to provide a sufficient root cause.

**Comment by ghost** [comment] 2019-05-30 23:55
For sure there are no directly 'serious' personal data in the log. That would be irresponsible.

Is there any a way to send you the entire log by PN?
I could prepare the entire log for you tomorrow so you can see all other plugin player names and so on if you ensure that you will only use this log for error-research and there is no third party that will see it. So you could get the pastern link by pn on spigot and I tell you here when I have send it

(yes, I know that this sounds exaggerated, but we want to ensure all player and server related data to be save. Including the used plugins due to errors player could maybe use)

**Comment by ghost** [comment] 2019-05-31 12:45
i maby found a way to avoid this bug in my purpose.
please just answer here: https://github.com/JCulley/ProQuests-Documentation/issues/201

if you want I can anyway send you the log file via spigot pn, cause I already prepared it.

**Comment by JCulley** [comment] 2019-05-31 14:58
Closing this then as no additional information has been provided and you have believed to have solved your own issue.

**Closed as completed by JCulley** 2019-05-31 14:58 UTC
Labels: Insufficient, No Action

**Comment by ghost** [comment] 2019-06-01 10:48
The error also occurs with mysql.
I will send you the prepared log via Spigot PN

**Comment by ghost** [comment] 2019-06-04 20:04
?

**Comment by JCulley** [comment] 2019-06-04 20:11
Answer was provided in the issue you requested a response on.  #201 

Locking this thread.
