### ISSUE TITLE
Chest Inventory Issues.

### ISSUE THREAD

**Issue by flrping** [JCulley/ProQuests-Documentation#235] opened 2019-01-04 02:52 UTC
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/flrping.238558/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - Latest
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - PaperSpigot 1.8.8
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/iZJGBUx1
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - Shift-right clicking issues. Just moving things out of chests this way causes it to go back. Many players have reported this to me once I re-added this  plugin to my server. This is the only plugin I added, and this started occurring. I have also tested this on a testing server, it happens there. Once I removed it, it has stopped. 

Edit: You hold shift, and right click to move the item from the chest into your player inventory. When you do this with the plugin installed (latest) the item goes into your inventory, but bugs back into the chest. Not allowing the player to quickly move items in their inventory.  
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - https://gyazo.com/196ea32e98999789e291bb24905f7670
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment] 2019-01-04 02:57
I cannot investigate if you do not provide the requested information. Include additional information/proof pertaining to the “issue”.

Additionally the log file you provided has no reference of ProQuests whatsoever, so I don’t understand how ProQuests can be the issue if your not even using it?

**Comment by flrping** [comment] 2019-01-04 03:00
There. I also updated the log file. Forgot to reinstall the plugin.

**Comment by JCulley** [comment] 2019-01-04 03:03
> Include additional information/proof pertaining to the “issue”.

Your description is so vague, and you have provided no media so I have no idea what the “issue” actually is. Please provide additional information.

**Comment by JCulley** [comment] 2019-01-04 03:05
Additionally your updated log file does not even show a single person joining the server, so how exactly did you recreate a menu “issue” if nobody had joined. Provide your entire log with the issue occurring.

**Comment by flrping** [comment] 2019-01-04 03:08
That is my test server log. Showing you a complete log of my actual server won't do much but let you read a bigger log. The issue occurs on both servers. I haven't touched the config on the test server, and I joined it now. It still occurs. If you want proof of my joining I'll be glad to send it. Is that better for you?

**Comment by flrping** [comment] 2019-01-04 03:13
Note: There is no error that appears in the console. You have no issue template, so I don't know where to put this.

**Comment by JCulley** [comment] 2019-01-04 03:14
I’m going to close this issue provided you don’t properly explain what the “issue” is. I have already asked you twice to provide additional information however you continue to skirt around simple requests. Regardless if you deem it necessary or not please provide the requested information. This will be the last time I ask.

**Comment by flrping** [comment] 2019-01-04 03:17
Your plugin doesn't let players move items in their inventory from chests without it bugging back into the chest. I clearly show it in the GIF. What is hard to understand? 

That is the issue.

**Comment by JCulley** [comment] 2019-01-04 03:21
Thanks I appreciate the attitude.

**Comment by flrping** [comment] 2019-01-04 03:22
You're asking me to explain something, and I have. It's pretty clear. Maybe try your own plugin?

**Closed as completed** 2019-01-04 03:23 UTC
Labels: Resolved, Implemented

**Comment by flrping** [comment] 2019-01-04 03:24
Alright.

**Comment by JCulley** [comment] 2019-01-04 03:50
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-give-players-objectives.18249/update?update=259265

**Comment by flrping** [comment] 2019-01-04 03:53
Thank you. I will be updating my review shortly.

**Comment by JCulley** [comment] 2019-01-04 03:57
No problem, I apologize for asking for so much information however it’s easier to solve issues when I have as large of a picture as possible because sometimes the root cause is very specific. Additionally when I asked the final time I didn’t realize you updated the original message which is why I didn’t know you had provided a GIF.

**Comment by flrping** [comment] 2019-01-04 03:59
All good.
