### ISSUE TITLE
FISH_QUEST | Catching drop works

### ISSUE THREAD

**Issue by Melowelsa** [JCulley/ProQuests-Documentation#241] opened 2019-01-27 21:03 UTC
➤ **Spigot account :**
➥ **https://www.spigotmc.org/members/__melowelei__.378949/**

➤ **Plugin version :**
➥ ProQuests : 2.1.1.3.1

➤ **Spigot Version :**
➥ git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

➤ **Information :**
➥ Bug : We can finish "FISH_QUEST" by taking a fishing rod and catching a drop, it count as fished.
➥ Reproduce : Drop an item in front of you, take your fishing rod and right-click the drop.

**Comment by JCulley** [comment] 2019-01-27 21:07
Please provide your log file and a detailed explanation. I don't really understand what the issue is as it wasn't described in a detailed manor.

**Comment by Melowelsa** [comment] 2019-01-28 11:44
➤ **Startup log :**
➥ **http://hatebin.com/lhkwqaubzj**
➤ **GIF :**
➥ **https://gph.is/2RSh1A0**

**Comment by JCulley** [comment] 2019-01-28 13:01
I would need your log file up until the point the issue occurs. ProQuests simply listens for the fishing event provided by Spigot if it interprets fishing for an entity itemstack to be a valid catch there’s not much I can do.

**Comment by Melowelsa** [comment] 2019-01-28 17:17
**http://hatebin.com/zshepiocwh**.

**Comment by JCulley** [comment] 2019-02-07 21:50
I've implemented a workaround so all catches are only counted if the block below the hook is water. This will be in the next release.

**Comment by JCulley** [comment] 2019-03-28 01:14
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-20-off-spring-sale-give-players-objectives.18249/update?update=270376

**Closed as completed by JCulley** 2019-03-28 01:14 UTC
Labels: Resolved, Implemented
