### ISSUE TITLE
Where is Quest Type - In Game

### ISSUE THREAD

**Issue by crston** [JCulley/ProQuests-Documentation#202] opened 2018-10-02 09:12 UTC
**Spigot account** - {insert here}
 https://www.spigotmc.org/members/38059

**Plugin version** - {insert here}
2.1.0.2-beta

**Spigot Version** - {insert here}
1.13.1

![2018-10-02_13 37 ### 45](https://user-images.githubusercontent.com/17114682/46339742-9434f180-c66e-11e8-89b1-b99f7367c542.png)

when in-game quest type?

**Comment by JCulley** [comment] 2018-10-02 09:23
Remove all of your reviews, follow the guidelines and actually provide all of the required information including a plaintext version of your log file on an online service such as pastebin. This barely follows any guidelines.

**Comment by crston** [comment] 2018-10-02 09:35
https://pastebin.com/awsMrZHy
and all review remove now.

**Comment by crston** [comment] 2018-10-02 09:37
https://pastebin.com/HrbzXBYf

this is error.

**Comment by JCulley** [comment] 2018-10-02 09:47
Provide your entire log.yml as requested.

**Comment by crston** [comment] 2018-10-02 10:05
Here.
[latest - 복사본.log](https://github.com/JCulley/ProQuests-Documentation/files/2437408/latest.-.log)

**Comment by JCulley** [comment] 2018-10-02 11:39
> [18:35:07] [Server thread/INFO]: crston issued server command: /plugman load proquests

Utilities such as PlugMan are not supported and cause miscellaneous issues. Try it again with a clean restart of Spigot. If the error persists then reply to this with an updated plaintext version of your log.

Additionally you still never followed the guidelines. As stated in the guidelines a clear explanation of the issue is required. Although it may be clear that the creator items seem to not appear I need to know the steps you took to get to this point, is it every time, were you doing something prior? I don't have time to investigate issues if you're not willing to put in the time to provide an adequate self analysis.

**Comment by crston** [comment] 2018-10-02 12:36
[latest - 복사본.log](https://github.com/JCulley/ProQuests-Documentation/files/2437812/latest.-.log)

![2018-10-02_13 37 45](https://user-images.githubusercontent.com/17114682/46348813-2a771080-c68b-11e8-9918-6e4bfea7dfa9.png)

One Page Quest Type not icon.

why?

**Comment by JCulley** [comment] 2018-10-02 12:39
> Additionally you still never followed the guidelines. As stated in the guidelines a clear explanation of the issue is required. Although it may be clear that the creator items seem to not appear I need to know the steps you took to get to this point, is it every time, were you doing something prior? I don't have time to investigate issues if you're not willing to put in the time to provide an adequate self analysis.

**Comment by crston** [comment] 2018-10-02 14:13
No... this is first file.. first config file.

**Comment by JCulley** [comment] 2018-10-07 16:06
The next update will contain a fix for this. In the future I will not investigate if you fail to provide a detailed analysis of the issue.

**Comment by JCulley** [comment] 2018-11-10 20:50
https://www.spigotmc.org/resources/proquests-1-7-1-13-1-give-players-objectives.18249/update?update=251793

**Closed as completed by JCulley** 2018-11-10 20:50 UTC
Labels: Resolved, Implemented
