### ISSUE TITLE
fish quest dont work error in console

### ISSUE THREAD

**Issue by TwerkRektDev** [JCulley/ProQuests-Documentation#333] opened 2020-02-10 01:33 UTC
**Spigot account** - https://www.spigotmc.org/members/twerkrekt.141957/
<br>

**Plugin version** - 2.1.1.15
<br>

**Spigot Version** - Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
<br>

**Link to log file** - https://code.alwyn974.re/eyoxumeqix.md
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - Hello, i have tested  many time for create fishing quests, all configuration are good but when player fishing i got a error in my console:
https://code.alwyn974.re/ovebisiwih.cs
<br>
https://hastebin.com/iyugokawux.cpp

**Additional media** - 
error: https://code.alwyn974.re/ovebisiwih.cs
config: https://code.alwyn974.re/elediyojuj.makefile

<br>

**Comment by JCulley** [comment] 2020-02-10 02:07
Unfortunately I do not provide support for forked versions or Spigot due to the number of incompatibilities which can occur like this one. The FishHook object is not used in the getHook method for PaperSpigot 1.12.2.

Duplicate of #281

**Closed as completed** 2020-02-10 02:07 UTC
Labels: No Action
